config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root to: 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30}
  validates :description, presence: true
  enum status: { '未着手':0, '着手中':1, '完了':2 }
  enum priority: { '高':0, '中':1, '低':2 }
  scope :search_title, -> (search_title) { where("title LIKE ?", "%#{search_title}%") }
  scope :search_status, -> (search_status) { where(status: search_status) }
  scope :seach_label, -> (search_label) { joins(:labels).where(search_label) }
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :must_login, only: [:index, :new, :show, :edit, :update, :destroy]

  def index
    if params[:search].present?
      if params[:title].present? && params[:status].present? && params[:label_id].present? #タイトルとステータスとラベルで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_title(params[:title]).search_status(params[:status]).seach_label(labels: { id: params[:label_id] })
      elsif params[:title].present? && params[:status].present? #タイトルとステータスで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_title(params[:title]).search_status(params[:status])
      elsif params[:title].present? && params[:label_id].present? #タイトルとラベルで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_title(params[:title]).seach_label(labels: { id: params[:label_id] })
      elsif params[:status].present? && params[:label_id].present? #ステータスとラベルで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_status(params[:status]).seach_label(labels: { id: params[:label_id] })
      elsif params[:title].present? #タイトルのみで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_title(params[:title])
      elsif params[:status].present? #ステータスのみで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).search_status(params[:status])
      else params[:label_id].present? #ラベルのみで検索する場合
        @tasks = Task.page(params[:page]).where(user_id: current_user.id).seach_label(labels: { id: params[:label_id] })
      end
    elsif params[:sort_expired]
      @tasks = Task.page(params[:page]).where(user_id: current_user.id).order(end_deadline: :asc) #終了期限の昇順に表示
    elsif params[:sort_priority]
      @tasks = Task.page(params[:page]).where(user_id: current_user.id).order(priority: :asc).order(end_deadline: :asc) #優先順位が高いものを終了期限の昇順に表示
    else
      @tasks = Task.page(params[:page]).where(user_id: current_user.id).order(created_at: :desc) #作成日時の降順に表示
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      flash[:success] = "タスク「#{@task.title}」を登録しました。"
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update!(task_params)
    flash[:success] = "タスク「#{task.title}」を更新しました。"
    redirect_to tasks_url
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    if current_user.admin?
      flash[:success] = "タスク「#{task.title}」を削除しました。"
      redirect_to admin_users_path
    else
      flash[:success] = "タスク「#{task.title}」を削除しました。"
      redirect_to tasks_url
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :end_deadline, :status, :priority, { label_ids: [] })
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
  <% if task.errors.present? %>
    <div id="error_explanation">
      <h2><%= task.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
</div>

<%= form_with(model: task, local: true) do |f| %>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <%= f.label :end_deadline %>
    <%= f.date_field :end_deadline, class: 'form-control' %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.keys, class: 'form-control' %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <%= f.label :priority %>
    <%= f.select :priority, Task.priorities.keys, class: 'form-control' %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= f.label :label, "ラベル" %>
      <%= f.collection_check_boxes(:label_ids, Label.all, :id, :name, include_hidden: false) %>
  </div>
  <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= f.submit t('helpers.submit.create'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3"><%= t('.task_edit') %></h2>

    <%= render partial: 'form', locals: { task: @task } %>

    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= link_to t('tasks.index.task_list'), tasks_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h2><%= t('.task_list') %></h2>
    <h3><%= t('.search_tasks') %></h3>
    <%= form_with class:"form-inline", url:tasks_path, method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, t('activerecord.attributes.task.title') %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :status, t('activerecord.attributes.task.status') %>
        <%= f.select :status, Task.statuses.keys, { include_blank: true, selected: '' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :label, t('activerecord.attributes.label.name') %>
        <%= f.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :search, value: 'true' %>
        <%= f.submit t('.search'), class: 'btn btn-primary'%><%= link_to t('.clear'), tasks_path, class: 'btn btn-danger' %>
      </div>
    <% end %>

    <br>
    <%= link_to t('directory.task_creation'), new_task_path, class: 'btn btn-info' %></li>
    <%= link_to t('.sort_by_end_deadline'), tasks_path(sort_expired: "true"), class: 'btn btn-info' %></li>
    <%= link_to t('.sort_by_priority'), tasks_path(sort_priority: "true"), class: 'btn btn-info' %></li>
    <br>

    <%= paginate @tasks %>
    <%= page_entries_info @tasks %>

    <table class="table table-hover table-striped table-sm">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.task.title') %></th>
          <th><%= t('activerecord.models.user') %></th>
          <th><%= t('activerecord.attributes.task.created_at') %></th>
          <th><%= t('activerecord.attributes.task.end_deadline') %></th>
          <th><%= t('activerecord.attributes.task.status') %></th>
          <th><%= t('activerecord.attributes.task.priority') %></th>
          <th><%= t('activerecord.models.label') %></th>
          <th><%= t('directory.edit') %></th>
          <th><%= t('directory.delete') %></th>
        </tr>
      </thead>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td class="task_row"><%= link_to task.title, task_path(task) %></td>
            <td><%= task.user.name %></td>
            <td><%= task.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            <td class="deadline_row"><%= task.end_deadline.strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= task.status %></td>
            <td class="priority_row"><%= task.priority %></td>
            <td>
              <% task.labels.each do |label| %>
                <%= label.name %>
              <% end %></td>
            <td><%= link_to t('directory.edit'), edit_task_path(task), class: 'btn btn-primary mr-3' %></td>
            <td><%= link_to t('directory.delete'), task, method: :delete, data: { confirm: "タスク「#{task.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3"><%= t('directory.task_creation') %></h2>

    <%= render partial: 'form', locals: { task: @task } %>

    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= link_to t('tasks.index.task_list'), tasks_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h2><%= t('.task_details') %></h2>

    <table class="table table-striped">
      <tbody>
        <tr>
          <th><%= t('activerecord.attributes.task.id') %></th>
          <td><%= @task.id %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.models.user') %></th>
          <td><%= @task.user.name %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.title') %></th>
          <td><%= @task.title %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.description') %></th>
          <td><%= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div") %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.end_deadline') %></th>
          <td><%= @task.end_deadline.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.status') %></th>
          <td><%= @task.status %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.priority') %></th>
          <td><%= @task.priority %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.models.label') %></th>
          <td>
            <% @task.labels.each do |label| %>
              <%= label.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.created_at') %></th>
          <td><%= @task.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.task.updated_at') %></th>
          <td><%= @task.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
      </tbody>
    </table>
    <%= link_to t('directory.edit'), edit_task_path, class: 'btn btn-primary mr-3' %>
    <%= link_to t('directory.delete'), @task, method: :delete, data: { confirm: "タスク「#{@task.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
    <%= link_to t('tasks.index.task_list'), tasks_path, class: 'btn btn-info' %>
  </div>
</div>