config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root to: 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :admin_exist_check
  before_update :admin_update_check
  has_many :tasks, :dependent => :destroy
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :update, allow_blank: true
  has_secure_password

  private
  def admin_exist_check
    if User.where(admin: true).count <= 1 && self.admin == true
      errors.add(:admin, "エラーです。管理ユーザーがいなくなるため、削除することはできません。")
      throw(:abort)
    end
  end

  def admin_update_check
    if User.where(admin: true).count == 1 && self.admin == false
      errors.add(:admin, "エラーです。管理ユーザーがいなくなるため、権限を外すことはできません。")
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index, :new, :edit]

  def new
    @user = User.new
  end

  def index
    @users = User.all.includes(:tasks).order(created_at: :asc).page(params[:page]).per(10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー「#{@user.name}」を登録しました。"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー「#{@user.name}」を更新しました。"
      redirect_to admin_users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:info] = "ユーザー「#{@user.name}」を削除しました。"
      redirect_to admin_users_path
    else
      flash[:danger] = "管理者がいなくなるため、削除することができません。"
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    if current_user.admin?
      return true
    else
      flash[:danger] = 'あなたは管理者ではありません。'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_signup, only: [:new]
  before_action :must_login, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザー「#{@user.name}」を登録しました！"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    if current_user.id == User.find(params[:id])[:id] # 他ユーザーのマイページにアクセスした場合、タスク一覧に遷移
      @user = User.find(params[:id])
    else
      redirect_to tasks_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <% if @user.errors.present? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <h2 class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3"><%= t('directory.user_edit') %></h2>
    <%= form_with(model: [:admin, @user], local: true) do |f| %>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-check col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :admin, class: 'form-check-label'%>
        <%= f.check_box :admin, class: 'form-check-input', id: 'input_admin' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.submit t('directory.registration'),class: 'btn btn-primary' %>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= link_to t('directory.user_list'), admin_users_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h2><%= t('directory.user_list') %></h2>

    <%= paginate @users %>
    <%= page_entries_info @users %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.user.name') %></th>
          <th><%= t('activerecord.attributes.user.email') %></th>
          <th><%= t('activerecord.attributes.user.admin') %></th>
          <th><%= t('activerecord.attributes.user.created_at') %></th>
          <th><%= t('activerecord.attributes.user.updated_at') %></th>
          <th><%= t('directory.task_counts') %></th>
          <th><%= t('directory.edit') %></th>
          <th><%= t('directory.delete') %></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, admin_user_path(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.admin %></td>
            <td><%= user.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= user.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= user.tasks.count %></td>
            <td><%= link_to t('directory.edit'), edit_admin_user_path(user), class: 'btn btn-primary mr-3' %></td>
            <td><%= link_to t('directory.delete'), admin_user_path(user), method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to t('directory.create_user'), new_admin_user_path, class: 'btn btn-info' %></li>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <% if @user.errors.present? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <h2 class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3"><%= t('directory.create_user') %></h2>
    <%= form_with(model: [:admin, @user], local: true) do |f| %>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-check col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :admin, class: 'form-check-label'%>
        <%= f.check_box :admin, class: 'form-check-input', id: 'input_admin' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <%= f.submit t('directory.registration'),class: 'btn btn-primary' %>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
      <%= link_to t('directory.user_list'), admin_users_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h2><%= @user.name %><%= t('users.show.my_page') %></h2>
    <%= link_to t('directory.user_list'), admin_users_path, class: 'btn btn-info' %>
    <h3><%= t('directory.user_details') %></h3>
    <table class="table table-striped">
      <tbody>
        <tr>
          <th><%= t('activerecord.attributes.user.name') %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.user.email') %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.user.admin') %></th>
          <td><%= @user.admin %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.user.created_at') %></th>
          <td><%= @user.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <tr>
          <th><%= t('activerecord.attributes.user.updated_at') %></th>
          <td><%= @user.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
      </tbody>
    </table>

    <h3><%= t('tasks.index.task_list') %></h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('activerecord.attributes.task.title') %></th>
          <th><%= t('activerecord.models.user') %></th>
          <th><%= t('activerecord.attributes.task.created_at') %></th>
          <th><%= t('activerecord.attributes.task.end_deadline') %></th>
          <th><%= t('activerecord.attributes.task.status') %></th>
          <th><%= t('activerecord.attributes.task.priority') %></th>
          <th><%= t('activerecord.models.label') %></th>
          <th><%= t('directory.edit') %></th>
          <th><%= t('directory.delete') %></th>
        </tr>
      </thead>
      <tbody>
        <% @user.tasks.each do |task| %>
        <tr>
          <td><%= link_to task.title, task_path(task) %></td>
          <td><%= task.user.name %></td>
          <td><%= task.created_at.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= task.end_deadline.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= task.status %></td>
          <td><%= task.priority %></td>
          <td>
            <% task.labels.each do |label| %>
              <%= label.name %>
            <% end %></td>
          <td><%= link_to t('directory.edit'), edit_task_path(task), class: 'btn btn-primary mr-3' %></td>
          <td><%= link_to t('directory.delete'), task, method: :delete, data: { confirm: "タスク「#{task.title}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>