config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root to: 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <header>
        <h1>TaskManagement App <small>  タスク管理アプリ</small></h1>
      </header>

      <!-- <div id="wrapper">
        <nav class="navbar navbar-default">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="navbar-item"><%= link_to t('directory.user_control'), admin_users_path %></li>
              <li class="navbar-item"><%= link_to t('directory.mypage'), user_path(current_user.id) %></li>
              <li class="navbar-item"><%= link_to t('directory.logout'), session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li class="navbar-item"><%= link_to t('directory.signup'), new_user_path %></li>
              <li class="navbar-item"><%= link_to t('directory.login'), new_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div> -->

        <nav class="navbar navbar-default">
          <!-- <a class="navbar-brand" href="/">TaskManagement App</a> -->
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li class="navbar-item"><%= link_to t('directory.user_control'), admin_users_path %></li>
                <li class="navbar-item"><%= link_to t('directory.mypage'), user_path(current_user.id) %></li>
                <li class="navbar-item"><%= link_to t('directory.logout'), session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li class="navbar-item"><%= link_to t('directory.signup'), new_user_path %></li>
                <li class="navbar-item"><%= link_to t('directory.login'), new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </nav>

      <% flash.each do |key, value| %>
        <p class="alert alert-<%= key %>">
          <%= value %>
        </p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>